# Generated by Django 4.2.5 on 2023-09-12 16:51

from django.db import migrations, models



# Função para criar usuário admin padrão
def create_admin_user(apps, schema_editor):
    User = apps.get_model('core', 'User')
    from django.contrib.auth.hashers import make_password
    if not User.objects.filter(email='admin@admin.com').exists():
        User.objects.create(
            email='admin@admin.com',
            password=make_password('admin'),
            is_admin=True,
            is_active=True
        )

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('forgot_password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('forgot_password_expire', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(
            code=create_admin_user,
            reverse_code=migrations.RunPython.noop
        ),
    ]

