# Generated by Django 4.2.5 on 2023-09-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_of_use', models.TextField(blank=True, null=True)),
                ('privacy_policy', models.TextField(blank=True, null=True)),
                ('support_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_menu', models.CharField(blank=True, choices=[('CONFIG', 'CONFIG'), ('CRUD', 'CRUD'), ('INSIDE WEB', 'INSIDE WEB')], max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('icon_web', models.TextField(blank=True, null=True)),
                ('router_link', models.CharField(blank=True, max_length=255, null=True)),
                ('config_url', models.CharField(blank=True, max_length=255, null=True)),
                ('list_url', models.CharField(blank=True, max_length=255, null=True)),
                ('get_by_id_url', models.CharField(blank=True, max_length=255, null=True)),
                ('post_url', models.CharField(blank=True, max_length=255, null=True)),
                ('patch_url', models.CharField(blank=True, max_length=255, null=True)),
                ('delete_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
