# Generated by Django 4.2.5 on 2025-09-18 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrudModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_model', models.CharField(max_length=150, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=150)),
                ('enable_list', models.BooleanField(default=True)),
                ('enable_get', models.BooleanField(default=True)),
                ('enable_create', models.BooleanField(default=False)),
                ('enable_update', models.BooleanField(default=False)),
                ('enable_delete', models.BooleanField(default=False)),
                ('default_ordering', models.CharField(blank=True, default='', max_length=120)),
                ('search_fields', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CRUD Model Config',
                'verbose_name_plural': 'CRUD Model Configs',
            },
        ),
        migrations.CreateModel(
            name='CrudFieldConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=120)),
                ('field_type', models.CharField(blank=True, default='', max_length=80)),
                ('include_in_list', models.BooleanField(default=False)),
                ('include_in_get', models.BooleanField(default=True)),
                ('include_in_create', models.BooleanField(default=False)),
                ('include_in_update', models.BooleanField(default=False)),
                ('required_on_create', models.BooleanField(default=False)),
                ('read_only', models.BooleanField(default=False)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('display_label', models.CharField(blank=True, default='', max_length=150)),
                ('model_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminweb.crudmodelconfig')),
            ],
            options={
                'ordering': ('order_index', 'id'),
                'unique_together': {('model_config', 'field_name')},
            },
        ),
    ]
